"""add_rentals_and_studio_reservations

Revision ID: 67353f3887f8
Revises: c21c0c510d40
Create Date: 2026-07-26 17:18:46.211652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67353f3887f8'
down_revision: Union[str, Sequence[str], None] = 'c21c0c510d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_for_rent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('daily_rate_ghs', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('imagekit_file_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_for_rent_slug'), 'equipment_for_rent', ['slug'], unique=True)
    op.create_table('rental_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('rental_days', sa.Integer(), nullable=False),
    sa.Column('total_price_ghs', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending_payment', 'paid', 'active', 'returned', 'cancelled', name='rental_status'), nullable=False),
    sa.Column('paystack_reference', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment_for_rent.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_requests_equipment_id'), 'rental_requests', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_rental_requests_user_id'), 'rental_requests', ['user_id'], unique=False)
    op.create_table('studio_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('requested_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requested_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'payment_pending', 'reserved', 'expired', 'cancelled', name='reservation_status'), nullable=False),
    sa.Column('approved_price_ghs', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deposit_amount_ghs', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('balance_due_ghs', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paystack_reference', sa.String(length=100), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studio_reservations_user_id'), 'studio_reservations', ['user_id'], unique=False)
    op.add_column(
        'booking_settings',
        sa.Column(
            'reservation_deposit_ghs',
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            server_default='50.00',
        ),
    )
    op.alter_column('booking_settings', 'reservation_deposit_ghs', server_default=None)
    op.execute("ALTER TYPE payment_purpose ADD VALUE IF NOT EXISTS 'rental_payment'")
    op.execute("ALTER TYPE payment_purpose ADD VALUE IF NOT EXISTS 'reservation_deposit'")
    op.add_column('payments', sa.Column('rental_request_id', sa.UUID(), nullable=True))
    op.add_column('payments', sa.Column('reservation_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_payments_rental_request_id'), 'payments', ['rental_request_id'], unique=False)
    op.create_index(op.f('ix_payments_reservation_id'), 'payments', ['reservation_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'rental_requests', ['rental_request_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'studio_reservations', ['reservation_id'], ['id'])
    op.add_column('receipts', sa.Column('rental_request_id', sa.UUID(), nullable=True))
    op.add_column('receipts', sa.Column('reservation_id', sa.UUID(), nullable=True))
    op.alter_column('receipts', 'booking_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_receipts_rental_request_id'), 'receipts', ['rental_request_id'], unique=False)
    op.create_index(op.f('ix_receipts_reservation_id'), 'receipts', ['reservation_id'], unique=False)
    op.create_foreign_key(None, 'receipts', 'rental_requests', ['rental_request_id'], ['id'])
    op.create_foreign_key(None, 'receipts', 'studio_reservations', ['reservation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipts', type_='foreignkey')
    op.drop_constraint(None, 'receipts', type_='foreignkey')
    op.drop_index(op.f('ix_receipts_reservation_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_rental_request_id'), table_name='receipts')
    op.alter_column('receipts', 'booking_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('receipts', 'reservation_id')
    op.drop_column('receipts', 'rental_request_id')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_reservation_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_rental_request_id'), table_name='payments')
    op.drop_column('payments', 'reservation_id')
    op.drop_column('payments', 'rental_request_id')
    op.drop_column('booking_settings', 'reservation_deposit_ghs')
    op.drop_index(op.f('ix_studio_reservations_user_id'), table_name='studio_reservations')
    op.drop_table('studio_reservations')
    op.drop_index(op.f('ix_rental_requests_user_id'), table_name='rental_requests')
    op.drop_index(op.f('ix_rental_requests_equipment_id'), table_name='rental_requests')
    op.drop_table('rental_requests')
    op.drop_index(op.f('ix_equipment_for_rent_slug'), table_name='equipment_for_rent')
    op.drop_table('equipment_for_rent')
    # ### end Alembic commands ###
