"""add session booking and payments

Revision ID: c21c0c510d40
Revises: 3236f6a5511a
Create Date: 2026-07-26 16:54:12.119389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c21c0c510d40'
down_revision: Union[str, Sequence[str], None] = '3236f6a5511a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_deposit_ghs', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_ghs', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_types_slug'), 'session_types', ['slug'], unique=True)
    op.create_table('studio_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studio_slots_starts_at'), 'studio_slots', ['starts_at'], unique=False)
    op.create_table('slot_holds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_type_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'converted', 'expired', 'released', name='hold_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_type_id'], ['session_types.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['studio_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slot_holds_slot_id'), 'slot_holds', ['slot_id'], unique=False)
    op.create_index(op.f('ix_slot_holds_user_id'), 'slot_holds', ['user_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('session_type_id', sa.UUID(), nullable=False),
    sa.Column('hold_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending_payment', 'confirmed', 'cancelled', name='booking_status'), nullable=False),
    sa.Column('deposit_amount_ghs', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price_ghs', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_due_ghs', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paystack_reference', sa.String(length=100), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hold_id'], ['slot_holds.id'], ),
    sa.ForeignKeyConstraint(['session_type_id'], ['session_types.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['studio_slots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_paystack_reference'), 'bookings', ['paystack_reference'], unique=False)
    op.create_index(op.f('ix_bookings_slot_id'), 'bookings', ['slot_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('amount_pesewas', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='payment_status'), nullable=False),
    sa.Column('purpose', sa.Enum('session_deposit', name='payment_purpose'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('paystack_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('reference', name='uq_payments_reference')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('amount_ghs', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id'),
    sa.UniqueConstraint('receipt_number', name='uq_receipts_number')
    )
    op.create_index(op.f('ix_receipts_booking_id'), 'receipts', ['booking_id'], unique=False)
    op.create_index(op.f('ix_receipts_user_id'), 'receipts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipts_user_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_booking_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_slot_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_paystack_reference'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_slot_holds_user_id'), table_name='slot_holds')
    op.drop_index(op.f('ix_slot_holds_slot_id'), table_name='slot_holds')
    op.drop_table('slot_holds')
    op.drop_index(op.f('ix_studio_slots_starts_at'), table_name='studio_slots')
    op.drop_table('studio_slots')
    op.drop_index(op.f('ix_session_types_slug'), table_name='session_types')
    op.drop_table('session_types')
    op.drop_table('booking_settings')
    # ### end Alembic commands ###
